import type { SocialIcons } from "@types";
import {
  TbBrandCodepen,
  TbBrandDiscord,
  TbBrandFacebook,
  TbBrandGithub,
  TbBrandGitlab,
  TbBrandInstagram,
  TbBrandLinkedin,
  TbBrandMastodon,
  TbBrandPinterest,
  TbBrandReddit,
  TbBrandSkype,
  TbBrandSnapchat,
  TbBrandSteam,
  TbBrandTelegram,
  TbBrandTiktok,
  TbBrandTwitch,
  TbBrandTwitter,
  TbBrandWhatsapp,
  TbBrandYoutube,
  TbMail,
} from "react-icons/tb/index";

const socialIcons: SocialIcons = {
  Github: TbBrandGithub,
  Facebook: TbBrandFacebook,
  Instagram: TbBrandInstagram,
  LinkedIn: TbBrandLinkedin,
  Mail: TbMail,
  Twitter: TbBrandTwitter,
  Twitch: TbBrandTwitch,
  YouTube: TbBrandYoutube,
  WhatsApp: TbBrandWhatsapp,
  Snapchat: TbBrandSnapchat,
  Pinterest: TbBrandPinterest,
  TikTok: TbBrandTiktok,
  CodePen: TbBrandCodepen,
  Discord: TbBrandDiscord,
  GitLab: TbBrandGitlab,
  Reddit: TbBrandReddit,
  Skype: TbBrandSkype,
  Steam: TbBrandSteam,
  Telegram: TbBrandTelegram,
  Mastodon: TbBrandMastodon,
};

export default socialIcons;
